# Generated by Django 3.0.5 on 2020-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assistant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'from_assistant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FromUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'from_user',
                'managed': False,
            },
        ),
    ]
