# Generated by Django 3.0.5 on 2020-05-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assistant_app', '0002_fromassistant_fromuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FromAssistant',
        ),
        migrations.DeleteModel(
            name='FromUser',
        ),
    ]
